import Head from 'next/head';
import Footer from '../components/Footer';
import Header from '../components/Header';

export default function Home() {
  return (
    <div id="container">
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />

      <main>
        <section className="hero">
          <div className="wrapper">
            <h1 className="title">
              Welcome to Prime Video
            </h1>
            <p className="subtitle">
              Join Prime Video to enjoy exclusive Amazon Originals as well as popular movies and TV shows. Watch now, cancel anytime.
            </p>
          </div>
          <div className="button-wrapper">
            <a className="button" href="#">Prime Video Member? Sign in
            </a>
            <div className='line'>
              <span className="dash1"> </span>
              <p className="or">
                or
              </p>
              <span className="dash2"> </span>
            </div>
          </div>
          <a className="button" href="#">Start your 7-day free trial*
          </a>
          <p className="price">Membership renews at USD 5.99/month.</p>
        </section>
        <section className='subhero'>
          <div className='wrapper'>
            <h1 className='title'>
              Great Entertainment
            </h1>
            <a className="button" href="#"> Start your free trial
            </a>
          </div>
        </section>
        <section className='features'>
          <div className='features-wrapper'>
            <div className='features-items'>
              <img src='https://m.media-amazon.com/images/G/52/digital/video/merch/2021/Other/PV_Benefits_Devices_UPDATED.png' alt='image1' />
              <h1 className='title'>
                Watch anywhere
              </h1>
              <p className='description'>
                Enjoy from the web or with the Prime Video app on your phone, tablet, or select Smart TVs — on up to 3 devices at once.
              </p>
            </div>

            <div className='features-items'>
              <img src='https://m.media-amazon.com/images/G/52/digital/video/merch/2021/Other/PV_Benefits_X-Ray_UPDATED.png' alt='image1' />
              <h1 className='title'>
                X-Ray for more
              </h1>
              <p className='description'>
                Use X-Ray for Movies and TV to identify actors and songs, explore actor bios, view trivia, and more.              </p>
            </div>

            <div className='features-items'>
              <img src='https://m.media-amazon.com/images/G/52/digital/video/merch/2021/Other/PV_Benefits_DataSaver_UPDATED.png' alt='image1' />
              <h1 className='title'>
                Data saver
              </h1>
              <p className='description'>
                Control data usage while downloading and watching videos on select phones or tablets.
              </p>
            </div>
          </div>

        </section>

        <section className='download'>
          <div className='wrapper'>
            <h1 className='title'>
              Download and go
            </h1>
            <p className='description'>
              Watch offline on the Prime Video app when you download titles to your iPhone, iPad, Tablet, or Android device.
            </p>
            <a className="button" href="#"> Start your free trial
            </a>


          </div>
        </section>

      </main>
      <Footer />

    </div>
  );
}
